"""A smoke pass over the UN card generator the workflow runs.

The generator lives in scripts/, outside the application, but the
application's import trusts what it produces — so the suite holds the two
ends of that contract together: filenames follow UN####_<MODALITY>.pdf, the
manifest's hashes match the files, several transport entries of one UN
number become pages of one PDF, unavailable modalities fail aloud, and the
store accepts a package the generator built.
"""
import importlib.util
import json
import sys
import zipfile
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]

pytest.importorskip("reportlab")


@pytest.fixture(scope="module")
def generator():
    sys.path.insert(0, str(REPO / "scripts"))
    spec = importlib.util.spec_from_file_location(
        "un_cards.generate", REPO / "scripts" / "un_cards" / "generate.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def generated(generator, tmp_path_factory):
    out = tmp_path_factory.mktemp("cards")
    report = generator.generate(["1203", "1263", "0004"],
                                ["ADR", "ADN", "IMDG", "RID", "ICAO"], out)
    manifest = generator.build_manifest(out, report)
    return out, report, manifest


def test_filenames_follow_the_contract(generated):
    out, report, _ = generated
    for row in report["results"]:
        if row["status"] != "generated":
            continue
        expected = f"{row['modality']}/UN{row['un_number']}_{row['modality']}.pdf"
        assert row["file"] == expected
        assert (out / expected).is_file()


def test_unavailable_modalities_fail_aloud(generated):
    _, report, _ = generated
    failed = {(r["un_number"], r["modality"])
              for r in report["results"] if r["status"] == "failed"}
    assert ("1203", "RID") in failed and ("1203", "ICAO") in failed
    reasons = [r["reason"] for r in report["results"] if r["status"] == "failed"]
    assert all(reason for reason in reasons)


def test_multiple_entries_become_pages_of_one_pdf(generated):
    """UN 1263 (PAINT) has packing groups I-III in table A: one file, several
    pages — never a silent pick of the first row."""
    _, report, _ = generated
    row = next(r for r in report["results"]
               if r["un_number"] == "1263" and r["modality"] == "ADR")
    assert row["status"] == "generated"
    assert row["pages"] >= 3


def test_the_manifest_matches_the_files(generated):
    import hashlib
    out, _, manifest = generated
    assert manifest["schema_version"] == 1
    assert manifest["total_cards"] > 0
    assert manifest["editions"]["ADR"] == "ADR 2025"
    for card in manifest["cards"]:
        content = (out / card["file"]).read_bytes()
        assert content.startswith(b"%PDF")
        assert hashlib.sha256(content).hexdigest() == card["sha256"]
        assert len(content) == card["size"]


def test_the_store_accepts_what_the_generator_packages(generated, generator,
                                                       tmp_path, monkeypatch):
    from app.core.config import get_settings
    out, _, manifest = generated
    package = tmp_path / "cargopilot-un-cards.zip"
    generator.build_zip(out, manifest, package)

    monkeypatch.setenv("DATA_DIR", str(tmp_path / "data"))
    get_settings.cache_clear()
    try:
        from app.services.documents import un_card_store
        result = un_card_store.import_package(package)
        assert result["imported"] == manifest["total_cards"]
        assert un_card_store.card_path("1203", "ADR") is not None
        assert un_card_store.card_path("1203", "RID") is None
    finally:
        get_settings.cache_clear()


def test_the_cards_carry_no_third_party_branding(generated):
    fitz = pytest.importorskip("fitz")
    out, _, manifest = generated
    for card in manifest["cards"][:6]:
        with fitz.open(str(out / card["file"])) as doc:
            text = "".join(page.get_text() for page in doc)
        assert "Generated by CargoPilot" in text
        assert "Cantell" not in text
        assert f"UN {card['un_number']}" in text or card["un_number"] in text
